In [2]:
import numpy as np 
import pandas as pd 
  
mldx_arrays = [np.array(['lion', 'lion', 'lion', 'bison', 
                         'bison', 'bison', 'hawk', 'hawk', 
                         'hawk']), 
                 
               np.array(['height', 'weight', 'speed', 
                         'height', 'weight', 'speed', 
                         'height', 'weight', 'speed'])] 
  
# creating a multi-index dataframe 
# with random data 
multiindex_df = pd.DataFrame( 
  np.random.randn(9, 4), index=mldx_arrays, 
  columns=['Type A', 'Type B', 'Type C', 'Type D']) 
  
multiindex_df.index.names = ['level 0', 'level 1'] 
multiindex_df

                   Type A    Type B    Type C    Type D
level 0 level 1
lion    height   0.111924 -0.751051  0.459716  0.452837
        weight  -2.211757 -0.543172 -0.315608  0.161329
        speed    0.384373 -0.244465  0.965478 -0.831504
bison   height  -0.332400 -0.357345  1.511525  0.546755
        weight   0.367792 -1.080343 -0.503992  0.457891
        speed    0.776146  0.176721 -0.588932 -1.302774
hawk    height  -1.478935 -2.146680 -0.027321  0.557200
        weight  -1.794084  0.327183 -0.970039  0.005286
        speed   -0.622082 -1.340785  0.807249  1.270921

### To drop the rows containing ‘lion’ in level 0.

In [3]:
multiindex_df.drop(labels='lion',level=0,axis=0)

                   Type A    Type B    Type C    Type D
level 0 level 1
bison   height  -0.332400 -0.357345  1.511525  0.546755
        weight   0.367792 -1.080343 -0.503992  0.457891
        speed    0.776146  0.176721 -0.588932 -1.302774
hawk    height  -1.478935 -2.146680 -0.027321  0.557200
        weight  -1.794084  0.327183 -0.970039  0.005286
        speed   -0.622082 -1.340785  0.807249  1.270921